//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;

namespace CRRD_Web_Interface {
    
    
    public partial class ManageItemOrganization {
        
        /// <summary>
        /// PanelErrorMessages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Panel PanelErrorMessages;
        
        /// <summary>
        /// LabelErrorMessageConnection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Label LabelErrorMessageConnection;
        
        /// <summary>
        /// PanelItemOrganization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Panel PanelItemOrganization;
        
        /// <summary>
        /// LiteralErrorMessageGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Literal LiteralErrorMessageGridView;
        
        /// <summary>
        /// LabelInstruction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Label LabelInstruction;
        
        /// <summary>
        /// DropDownListItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected DropDownList DropDownListItems;
        
        /// <summary>
        /// GridViewItemOrganization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected GridView GridViewItemOrganization;
    }
}
