use cs419-g2;

CREATE TABLE Organization (
	GUID VARCHAR(36) NOT NULL PRIMARY KEY,
	Name NVARCHAR(72) NOT NULL,
	Phone VARCHAR(10) default NULL,
	AddressLine1 NVARCHAR(72) default NULL,
	AddressLine2 NVARCHAR(72) default NULL,
	AddressLine3 NVARCHAR(72) default NULL,
	ZipCode VARCHAR(5) default NULL,
	Website NVARCHAR(72) default NULL,
	Hours NVARCHAR(72) default NULL,
	Notes NVARCHAR(256) default NULL
);

CREATE TABLE Item (
	GUID VARCHAR(36) NOT NULL PRIMARY KEY,
	Name NVARCHAR(72) NOT NULL
);

CREATE TABLE Category (
	GUID VARCHAR(36) NOT NULL PRIMARY KEY,
	Name NVARCHAR(72) NOT NULL
);

CREATE TABLE CategoryItem (
	CategoryGUID VARCHAR(36) NOT NULL,
	ItemGUID VARCHAR(36) NOT NULL,
	FOREIGN KEY (CategoryGUID) REFERENCES Category(GUID),
	FOREIGN KEY (ItemGUID) REFERENCES Item(GUID)
);

CREATE TABLE RepairOrganizationItem (
	OrganizationGUID VARCHAR(36) NOT NULL,
	ItemGUID VARCHAR(36) NOT NULL,
	FOREIGN KEY (OrganizationGUID) REFERENCES Organization(GUID),
	FOREIGN KEY (ItemGUID) REFERENCES Item(GUID)
);

CREATE TABLE ReuseOrganizationItem (
	OrganizationGUID VARCHAR(36) NOT NULL,
	ItemGUID VARCHAR(36) NOT NULL,
	FOREIGN KEY (OrganizationGUID) REFERENCES Organization(GUID),
	FOREIGN KEY (ItemGUID) REFERENCES Item(GUID)
);